// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Workflows.Item.Revisions;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Workflows.Item.Units;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.Wf.Api.Standard.V2.Workflows.Item {
    /// <summary>
    /// Builds and executes requests for operations under \wf\api\standard\v2\workflows\{workflowId}
    /// </summary>
    public class WithWorkflowItemRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The revisions property</summary>
        public RevisionsRequestBuilder Revisions
        {
            get => new RevisionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The units property</summary>
        public UnitsRequestBuilder Units
        {
            get => new UnitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithWorkflowItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkflowItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/workflows/{workflowId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithWorkflowItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkflowItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/workflows/{workflowId}", rawUrl)
        {
        }
    }
}
