// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Units.Item;
using NasokiKoide.DXSuite.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Units {
    /// <summary>
    /// Builds and executes requests for operations under \ConsoleWeb\api\v1\reading\units
    /// </summary>
    public class UnitsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the NasokiKoide.DXSuite.ConsoleWeb.api.v1.reading.units.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="UnitsItemRequestBuilder"/></returns>
        public UnitsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new UnitsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/units{?createdFrom*,createdTo*,docsetId*,documentId*,name*,readingUnitId*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/units{?createdFrom*,createdTo*,docsetId*,documentId*,name*,readingUnitId*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// 読取ユニットを検索します。
        /// </summary>
        /// <returns>A List&lt;Model__reading_units__GetReadingUnitsResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="Model__error_response_v1__ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<Model__reading_units__GetReadingUnitsResponse>?> GetAsync(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<Model__reading_units__GetReadingUnitsResponse>> GetAsync(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"400", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"401", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"404", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"500", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"XXX", Model__error_response_v1__ErrorResponse.CreateFromDiscriminatorValue},
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<Model__reading_units__GetReadingUnitsResponse>(requestInfo, Model__reading_units__GetReadingUnitsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.ToList();
        }
        /// <summary>
        /// 読取ユニットを検索します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="UnitsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public UnitsRequestBuilder WithUrl(string rawUrl)
        {
            return new UnitsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 読取ユニットを検索します。
        /// </summary>
        public class UnitsRequestBuilderGetQueryParameters 
        {
            /// <summary>yyyy-mm-dd HH:MM:SSで指定</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdFrom")]
            public string? CreatedFrom { get; set; }
#nullable restore
#else
            [QueryParameter("createdFrom")]
            public string CreatedFrom { get; set; }
#endif
            /// <summary>yyyy-mm-dd HH:MM:SSで指定</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdTo")]
            public string? CreatedTo { get; set; }
#nullable restore
#else
            [QueryParameter("createdTo")]
            public string CreatedTo { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能。※フォルダID、ドキュメントID、読取ユニットIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("docsetId")]
            public string? DocsetId { get; set; }
#nullable restore
#else
            [QueryParameter("docsetId")]
            public string DocsetId { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能。※フォルダID、ドキュメントID、読取ユニットIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("documentId")]
            public string? DocumentId { get; set; }
#nullable restore
#else
            [QueryParameter("documentId")]
            public string DocumentId { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能。※フォルダID、ドキュメントID、読取ユニットIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("readingUnitId")]
            public string? ReadingUnitId { get; set; }
#nullable restore
#else
            [QueryParameter("readingUnitId")]
            public string ReadingUnitId { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class UnitsRequestBuilderGetRequestConfiguration : RequestConfiguration<UnitsRequestBuilderGetQueryParameters> 
        {
        }
    }
}
