// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Workflows.Item.Revisions.Item.Configuration;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.Wf.Api.Standard.V2.Workflows.Item.Revisions.Item {
    /// <summary>
    /// Builds and executes requests for operations under \wf\api\standard\v2\workflows\{workflowId}\revisions\{revision}
    /// </summary>
    public class WithRevisionItemRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The configuration property</summary>
        public ConfigurationRequestBuilder Configuration
        {
            get => new ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithRevisionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRevisionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/workflows/{workflowId}/revisions/{revision}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithRevisionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRevisionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/workflows/{workflowId}/revisions/{revision}", rawUrl)
        {
        }
    }
}
