// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Units.Item.Delete;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Units.Item.Export;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Units.Item.PartsDownload;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Units.Item {
    /// <summary>
    /// Builds and executes requests for operations under \ConsoleWeb\api\v1\reading\units\{id}
    /// </summary>
    public class UnitsItemRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The deletePath property</summary>
        public DeleteRequestBuilder DeletePath
        {
            get => new DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The export property</summary>
        public ExportRequestBuilder Export
        {
            get => new ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partsDownload property</summary>
        public PartsDownloadRequestBuilder PartsDownload
        {
            get => new PartsDownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/units/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/units/{id}", rawUrl)
        {
        }
    }
}
