// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Pages;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Parts;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Units;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading {
    /// <summary>
    /// Builds and executes requests for operations under \ConsoleWeb\api\v1\reading
    /// </summary>
    public class ReadingRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The pages property</summary>
        public PagesRequestBuilder Pages
        {
            get => new PagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parts property</summary>
        public PartsRequestBuilder Parts
        {
            get => new PartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The units property</summary>
        public UnitsRequestBuilder Units
        {
            get => new UnitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ReadingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReadingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ReadingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReadingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading", rawUrl)
        {
        }
    }
}
