// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Pages.Add;
using NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Pages.Images;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Pages {
    /// <summary>
    /// Builds and executes requests for operations under \ConsoleWeb\api\v1\reading\pages
    /// </summary>
    public class PagesRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The add property</summary>
        public AddRequestBuilder Add
        {
            get => new AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The images property</summary>
        public ImagesRequestBuilder Images
        {
            get => new ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="PagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/pages", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="PagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/pages", rawUrl)
        {
        }
    }
}
