// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.Item.CsvEscaped;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.Item.Delete;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.Item.DownloadPartsImage;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.Item {
    /// <summary>
    /// Builds and executes requests for operations under \wf\api\standard\v2\units\{unitId}
    /// </summary>
    public class WithUnitItemRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The csv property</summary>
        public CsvRequestBuilder Csv
        {
            get => new CsvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public DeleteRequestBuilder DeletePath
        {
            get => new DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The downloadPartsImage property</summary>
        public DownloadPartsImageRequestBuilder DownloadPartsImage
        {
            get => new DownloadPartsImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithUnitItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUnitItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/units/{unitId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithUnitItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUnitItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/units/{unitId}", rawUrl)
        {
        }
    }
}
