// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Models;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Workflows.Item.Units.Ids;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NasokiKoide.DXSuite.Wf.Api.Standard.V2.Workflows.Item.Units {
    /// <summary>
    /// Builds and executes requests for operations under \wf\api\standard\v2\workflows\{workflowId}\units
    /// </summary>
    public class UnitsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The ids property</summary>
        public IdsRequestBuilder Ids
        {
            get => new IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/workflows/{workflowId}/units", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/workflows/{workflowId}/units", rawUrl)
        {
        }
        /// <summary>
        /// ワークフローに読取ユニットを登録します。
        /// </summary>
        /// <returns>A <see cref="RegisterReadingUnitResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="BadRequestErrorUnitResistResponse">When receiving a 400 status code</exception>
        /// <exception cref="UnAuthorizedErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="SpecifiedResourceDoesNotExistResponse">When receiving a 404 status code</exception>
        /// <exception cref="BadRequestErrorNotAcceptableResponse">When receiving a 409 status code</exception>
        /// <exception cref="InternalServerErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="Model__error_response_v2__ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<RegisterReadingUnitResponse?> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<RegisterReadingUnitResponse> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"400", BadRequestErrorUnitResistResponse.CreateFromDiscriminatorValue},
                {"401", UnAuthorizedErrorResponse.CreateFromDiscriminatorValue},
                {"404", SpecifiedResourceDoesNotExistResponse.CreateFromDiscriminatorValue},
                {"409", BadRequestErrorNotAcceptableResponse.CreateFromDiscriminatorValue},
                {"500", InternalServerErrorResponse.CreateFromDiscriminatorValue},
                {"XXX", Model__error_response_v2__ErrorResponse.CreateFromDiscriminatorValue},
            };
            return await RequestAdapter.SendAsync<RegisterReadingUnitResponse>(requestInfo, RegisterReadingUnitResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ワークフローに読取ユニットを登録します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="UnitsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public UnitsRequestBuilder WithUrl(string rawUrl)
        {
            return new UnitsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class UnitsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters> 
        {
        }
    }
}
