// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.ConsoleWeb.Api;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.ConsoleWeb {
    /// <summary>
    /// Builds and executes requests for operations under \ConsoleWeb
    /// </summary>
    public class ConsoleWebRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The api property</summary>
        public ApiRequestBuilder Api
        {
            get => new ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ConsoleWebRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConsoleWebRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ConsoleWebRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConsoleWebRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb", rawUrl)
        {
        }
    }
}
