// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Sorter.Api.V1.Add;
using NasokiKoide.DXSuite.Sorter.Api.V1.CsvDownload;
using NasokiKoide.DXSuite.Sorter.Api.V1.Delete;
using NasokiKoide.DXSuite.Sorter.Api.V1.Send;
using NasokiKoide.DXSuite.Sorter.Api.V1.Sorting;
using NasokiKoide.DXSuite.Sorter.Api.V1.Status;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.Sorter.Api.V1 {
    /// <summary>
    /// Builds and executes requests for operations under \Sorter\api\v1
    /// </summary>
    public class V1RequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The add property</summary>
        public AddRequestBuilder Add
        {
            get => new AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The csvDownload property</summary>
        public CsvDownloadRequestBuilder CsvDownload
        {
            get => new CsvDownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public DeleteRequestBuilder DeletePath
        {
            get => new DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send property</summary>
        public SendRequestBuilder Send
        {
            get => new SendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sorting property</summary>
        public SortingRequestBuilder Sorting
        {
            get => new SortingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public StatusRequestBuilder Status
        {
            get => new StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Sorter/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Sorter/api/v1", rawUrl)
        {
        }
    }
}
