// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Models;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.DataItems;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.Images;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.Item;
using NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.StatusWithUnitId;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units {
    /// <summary>
    /// Builds and executes requests for operations under \wf\api\standard\v2\units
    /// </summary>
    public class UnitsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The dataItems property</summary>
        public DataItemsRequestBuilder DataItems
        {
            get => new DataItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The images property</summary>
        public ImagesRequestBuilder Images
        {
            get => new ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the NasokiKoide.DXSuite.wf.api.standard.v2.units.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithUnitItemRequestBuilder"/></returns>
        public WithUnitItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("unitId", position);
                return new WithUnitItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/units{?createdFrom*,createdTo*,folderId*,status*,unitId*,unitName*,workflowId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="UnitsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnitsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/units{?createdFrom*,createdTo*,folderId*,status*,unitId*,unitName*,workflowId*}", rawUrl)
        {
        }
        /// <summary>
        /// 登録済みのユニット情報を取得します。
        /// </summary>
        /// <returns>A <see cref="Model__intelligent_ocr__GetReadingUnitsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="BadRequestErrorUnitSearchResponse">When receiving a 400 status code</exception>
        /// <exception cref="UnAuthorizedErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="SpecifiedResourceDoesNotExistResponse">When receiving a 404 status code</exception>
        /// <exception cref="InternalServerErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="Model__error_response_v2__ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Model__intelligent_ocr__GetReadingUnitsResponse?> GetAsync(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Model__intelligent_ocr__GetReadingUnitsResponse> GetAsync(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"400", BadRequestErrorUnitSearchResponse.CreateFromDiscriminatorValue},
                {"401", UnAuthorizedErrorResponse.CreateFromDiscriminatorValue},
                {"404", SpecifiedResourceDoesNotExistResponse.CreateFromDiscriminatorValue},
                {"500", InternalServerErrorResponse.CreateFromDiscriminatorValue},
                {"XXX", Model__error_response_v2__ErrorResponse.CreateFromDiscriminatorValue},
            };
            return await RequestAdapter.SendAsync<Model__intelligent_ocr__GetReadingUnitsResponse>(requestInfo, Model__intelligent_ocr__GetReadingUnitsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Builds and executes requests for operations under \wf\api\standard\v2\units\status?unitId={unitId}
        /// </summary>
        /// <returns>A <see cref="StatusWithUnitIdRequestBuilder"/></returns>
        /// <param name="unitId">The path parameter: unitId</param>
        public StatusWithUnitIdRequestBuilder StatusWithUnitId(string unitId)
        {
            if(string.IsNullOrEmpty(unitId)) throw new ArgumentNullException(nameof(unitId));
            return new StatusWithUnitIdRequestBuilder(PathParameters, RequestAdapter, unitId);
        }
        /// <summary>
        /// 登録済みのユニット情報を取得します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<UnitsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="UnitsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public UnitsRequestBuilder WithUrl(string rawUrl)
        {
            return new UnitsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 登録済みのユニット情報を取得します。
        /// </summary>
        public class UnitsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdFrom")]
            public string? CreatedFrom { get; set; }
#nullable restore
#else
            [QueryParameter("createdFrom")]
            public string CreatedFrom { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("createdTo")]
            public string? CreatedTo { get; set; }
#nullable restore
#else
            [QueryParameter("createdTo")]
            public string CreatedTo { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能。{folderId}、{workflowId}、{unitId} はいずれか1つのみ必須となります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("folderId")]
            public string? FolderId { get; set; }
#nullable restore
#else
            [QueryParameter("folderId")]
            public string FolderId { get; set; }
#endif
            /// <summary>ステータスを複数指定する場合、カンマ区切りで指定可能です。2: データ化中, 13: データチェック中, 15: コンペア中, 16: コンペア完了, 22: CSVダウンロード済</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能。{folderId}、{workflowId}、{unitId} はいずれか1つのみ必須となります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("unitId")]
            public string? UnitId { get; set; }
#nullable restore
#else
            [QueryParameter("unitId")]
            public string UnitId { get; set; }
#endif
            /// <summary>1〜128文字まで指定できます。日本語で設定する場合は、URLエンコードして設定します。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("unitName")]
            public string? UnitName { get; set; }
#nullable restore
#else
            [QueryParameter("unitName")]
            public string UnitName { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能。{folderId}、{workflowId}、{unitId} はいずれか1つのみ必須となります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workflowId")]
            public string? WorkflowId { get; set; }
#nullable restore
#else
            [QueryParameter("workflowId")]
            public string WorkflowId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class UnitsRequestBuilderGetRequestConfiguration : RequestConfiguration<UnitsRequestBuilderGetQueryParameters> 
        {
        }
    }
}
