// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NasokiKoide.DXSuite.Wf.Api.Standard.V2.Units.DataItems {
    /// <summary>
    /// Builds and executes requests for operations under \wf\api\standard\v2\units\dataItems
    /// </summary>
    public class DataItemsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>
        /// Instantiates a new <see cref="DataItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataItemsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/units/dataItems{?dataItemId*,detailDataItemId*,pageId*,unitId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="DataItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataItemsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api/standard/v2/units/dataItems{?dataItemId*,detailDataItemId*,pageId*,unitId*}", rawUrl)
        {
        }
        /// <summary>
        /// 登録済みユニットの読取パーツ情報を取得します。
        /// </summary>
        /// <returns>A <see cref="GetDataItemsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="BadRequestErrorReadPartsGetResponse">When receiving a 400 status code</exception>
        /// <exception cref="UnAuthorizedErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="SpecifiedResourceDoesNotExistResponse">When receiving a 404 status code</exception>
        /// <exception cref="NotAcceptableErrorResponse">When receiving a 406 status code</exception>
        /// <exception cref="InternalServerErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="Model__error_response_v2__ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<GetDataItemsResponse?> GetAsync(Action<RequestConfiguration<DataItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<GetDataItemsResponse> GetAsync(Action<RequestConfiguration<DataItemsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"400", BadRequestErrorReadPartsGetResponse.CreateFromDiscriminatorValue},
                {"401", UnAuthorizedErrorResponse.CreateFromDiscriminatorValue},
                {"404", SpecifiedResourceDoesNotExistResponse.CreateFromDiscriminatorValue},
                {"406", NotAcceptableErrorResponse.CreateFromDiscriminatorValue},
                {"500", InternalServerErrorResponse.CreateFromDiscriminatorValue},
                {"XXX", Model__error_response_v2__ErrorResponse.CreateFromDiscriminatorValue},
            };
            return await RequestAdapter.SendAsync<GetDataItemsResponse>(requestInfo, GetDataItemsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 登録済みユニットの読取パーツ情報を取得します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DataItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DataItemsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="DataItemsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public DataItemsRequestBuilder WithUrl(string rawUrl)
        {
            return new DataItemsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 登録済みユニットの読取パーツ情報を取得します。
        /// </summary>
        public class DataItemsRequestBuilderGetQueryParameters 
        {
            /// <summary>読取パーツIDはカンマ区切りで複数指定が可能です。但し、複数ユニットに跨る読取パーツIDの指定はできません。{unitId}、{pageId}、{dataItemId}、{detailDataItemId} はいずれか1つのみ必須となります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("dataItemId")]
            public string? DataItemId { get; set; }
#nullable restore
#else
            [QueryParameter("dataItemId")]
            public string DataItemId { get; set; }
#endif
            /// <summary>分割読取パーツIDはカンマ区切りで複数指定が可能です。但し、複数ユニットに跨る分割読取パーツIDの指定はできません。{unitId}、{pageId}、{dataItemId}、{detailDataItemId} はいずれか1つのみ必須となります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("detailDataItemId")]
            public string? DetailDataItemId { get; set; }
#nullable restore
#else
            [QueryParameter("detailDataItemId")]
            public string DetailDataItemId { get; set; }
#endif
            /// <summary>ページIDはカンマ区切りで複数指定が可能です。但し、複数ユニットに跨るページIDの指定はできません。{unitId}、{pageId}、{dataItemId}、{detailDataItemId} はいずれか1つのみ必須となります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageId")]
            public string? PageId { get; set; }
#nullable restore
#else
            [QueryParameter("pageId")]
            public string PageId { get; set; }
#endif
            /// <summary>1つのユニットのみ指定可能です。{unitId}、{pageId}、{dataItemId}、{detailDataItemId} はいずれか1つのみ必須となります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("unitId")]
            public string? UnitId { get; set; }
#nullable restore
#else
            [QueryParameter("unitId")]
            public string UnitId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class DataItemsRequestBuilderGetRequestConfiguration : RequestConfiguration<DataItemsRequestBuilderGetQueryParameters> 
        {
        }
    }
}
