// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace NasokiKoide.DXSuite.Models {
    #pragma warning disable CS1591
    public class AtypicalResultPart_bbox : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The height property</summary>
        public float? Height { get; set; }
        /// <summary>The width property</summary>
        public float? Width { get; set; }
        /// <summary>The x property</summary>
        public float? X { get; set; }
        /// <summary>The y property</summary>
        public float? Y { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="AtypicalResultPart_bbox"/> and sets the default values.
        /// </summary>
        public AtypicalResultPart_bbox()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="AtypicalResultPart_bbox"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static AtypicalResultPart_bbox CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new AtypicalResultPart_bbox();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"height", n => { Height = n.GetFloatValue(); } },
                {"width", n => { Width = n.GetFloatValue(); } },
                {"x", n => { X = n.GetFloatValue(); } },
                {"y", n => { Y = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("height", Height);
            writer.WriteFloatValue("width", Width);
            writer.WriteFloatValue("x", X);
            writer.WriteFloatValue("y", Y);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
