// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace NasokiKoide.DXSuite.Models {
    #pragma warning disable CS1591
    public class AtypicalResultOcrResult : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>回転角度&lt;br&gt;上を0度として右回りの回転角度</summary>
        public float? DeskewAngle { get; set; }
        /// <summary>The pageNum property</summary>
        public int? PageNum { get; set; }
        /// <summary>The parts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<AtypicalResultPart>? Parts { get; set; }
#nullable restore
#else
        public List<AtypicalResultPart> Parts { get; set; }
#endif
        /// <summary>処理状態&lt;br&gt;2: 読取完了&lt;br&gt;3: 読取失敗</summary>
        public int? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="AtypicalResultOcrResult"/> and sets the default values.
        /// </summary>
        public AtypicalResultOcrResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="AtypicalResultOcrResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static AtypicalResultOcrResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new AtypicalResultOcrResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"deskewAngle", n => { DeskewAngle = n.GetFloatValue(); } },
                {"pageNum", n => { PageNum = n.GetIntValue(); } },
                {"parts", n => { Parts = n.GetCollectionOfObjectValues<AtypicalResultPart>(AtypicalResultPart.CreateFromDiscriminatorValue)?.ToList(); } },
                {"status", n => { Status = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("deskewAngle", DeskewAngle);
            writer.WriteIntValue("pageNum", PageNum);
            writer.WriteCollectionOfObjectValues<AtypicalResultPart>("parts", Parts);
            writer.WriteIntValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
