// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace NasokiKoide.DXSuite.Models {
    #pragma warning disable CS1591
    public class GetReadingUnitsStatusResponse : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>0: データ化中、またはデータチェック未完了、またはコンペア未完了、または, 100: CSV未ダウンロード, 400: CSVダウンロード完了</summary>
        public int? CsvDownloadStatus { get; set; }
        /// <summary>0: データチェック設定無し、またはデータ化未完了, 200: データチェック中, 400: データチェック完了</summary>
        public int? DataCheckStatus { get; set; }
        /// <summary>0: データ化中、またはデータチェック中、またはデータチェック完了かつコンペア対象無し, 200: コンペア中, 400: コンペア完了</summary>
        public int? DataCompareStatus { get; set; }
        /// <summary>0: ページアップロード中(ページ分割中を含む), 200: データ化中, 400: データ化完了, 600: 一部データ化失敗</summary>
        public int? DataProcessingStatus { get; set; }
        /// <summary>0: パーツ画像生成対象無し、1: パーツ画像生成中、2: パーツ画像生成完了、3: パーツ画像生成一部失敗、4: パーツ画像生成エラー</summary>
        public int? PartsImageCreationStatus { get; set; }
        /// <summary>The revision property</summary>
        public int? Revision { get; set; }
        /// <summary>The unitId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitId { get; set; }
#nullable restore
#else
        public string UnitId { get; set; }
#endif
        /// <summary>The unitName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitName { get; set; }
#nullable restore
#else
        public string UnitName { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The workflowId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="GetReadingUnitsStatusResponse"/> and sets the default values.
        /// </summary>
        public GetReadingUnitsStatusResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="GetReadingUnitsStatusResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static GetReadingUnitsStatusResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new GetReadingUnitsStatusResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"createdAt", n => { CreatedAt = n.GetStringValue(); } },
                {"csvDownloadStatus", n => { CsvDownloadStatus = n.GetIntValue(); } },
                {"dataCheckStatus", n => { DataCheckStatus = n.GetIntValue(); } },
                {"dataCompareStatus", n => { DataCompareStatus = n.GetIntValue(); } },
                {"dataProcessingStatus", n => { DataProcessingStatus = n.GetIntValue(); } },
                {"partsImageCreationStatus", n => { PartsImageCreationStatus = n.GetIntValue(); } },
                {"revision", n => { Revision = n.GetIntValue(); } },
                {"unitId", n => { UnitId = n.GetStringValue(); } },
                {"unitName", n => { UnitName = n.GetStringValue(); } },
                {"updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
                {"workflowId", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteIntValue("csvDownloadStatus", CsvDownloadStatus);
            writer.WriteIntValue("dataCheckStatus", DataCheckStatus);
            writer.WriteIntValue("dataCompareStatus", DataCompareStatus);
            writer.WriteIntValue("dataProcessingStatus", DataProcessingStatus);
            writer.WriteIntValue("partsImageCreationStatus", PartsImageCreationStatus);
            writer.WriteIntValue("revision", Revision);
            writer.WriteStringValue("unitId", UnitId);
            writer.WriteStringValue("unitName", UnitName);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("workflowId", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
