// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace NasokiKoide.DXSuite.Models {
    #pragma warning disable CS1591
    public class SearchSortingUnitResponse : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The errorCode property</summary>
        public int? ErrorCode { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The pageCountAll property</summary>
        public int? PageCountAll { get; set; }
        /// <summary>success: 正常, error: エラー</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The statusCode property</summary>
        public int? StatusCode { get; set; }
        /// <summary>The statusList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<NasokiKoide.DXSuite.Models.Status>? StatusList { get; set; }
#nullable restore
#else
        public List<NasokiKoide.DXSuite.Models.Status> StatusList { get; set; }
#endif
        /// <summary>The statusName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusName { get; set; }
#nullable restore
#else
        public string StatusName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="SearchSortingUnitResponse"/> and sets the default values.
        /// </summary>
        public SearchSortingUnitResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="SearchSortingUnitResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static SearchSortingUnitResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new SearchSortingUnitResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"errorCode", n => { ErrorCode = n.GetIntValue(); } },
                {"message", n => { Message = n.GetStringValue(); } },
                {"pageCountAll", n => { PageCountAll = n.GetIntValue(); } },
                {"status", n => { Status = n.GetStringValue(); } },
                {"statusCode", n => { StatusCode = n.GetIntValue(); } },
                {"statusList", n => { StatusList = n.GetCollectionOfObjectValues<NasokiKoide.DXSuite.Models.Status>(NasokiKoide.DXSuite.Models.Status.CreateFromDiscriminatorValue)?.ToList(); } },
                {"statusName", n => { StatusName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("errorCode", ErrorCode);
            writer.WriteStringValue("message", Message);
            writer.WriteIntValue("pageCountAll", PageCountAll);
            writer.WriteStringValue("status", Status);
            writer.WriteIntValue("statusCode", StatusCode);
            writer.WriteCollectionOfObjectValues<NasokiKoide.DXSuite.Models.Status>("statusList", StatusList);
            writer.WriteStringValue("statusName", StatusName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
