// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace NasokiKoide.DXSuite.Models {
    #pragma warning disable CS1591
    public class SortingUnitCSVResponseV2 : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>CSVの値(ヘッダー、ボディ)がレスポンスとして戻ります。(上記サンプルのようにCSVファイルの保存先を指定すると、指定したフォルダにCSVファイルがダウンロードされます)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Csv内容 { get; set; }
#nullable restore
#else
        public string Csv内容 { get; set; }
#endif
        /// <summary>curl &quot;&lt;request-host&gt;/sorter/csvDownload&quot; -X POST -H &quot;apikey:xxxxxxxxxxxxxxxxxxx&quot; -d &quot;sortUnitId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&quot; &gt;C:\API\sample.csv</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sampleコード { get; set; }
#nullable restore
#else
        public string Sampleコード { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="SortingUnitCSVResponseV2"/> and sets the default values.
        /// </summary>
        public SortingUnitCSVResponseV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="SortingUnitCSVResponseV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static SortingUnitCSVResponseV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new SortingUnitCSVResponseV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"csv内容", n => { Csv内容 = n.GetStringValue(); } },
                {"sampleコード", n => { Sampleコード = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("csv内容", Csv内容);
            writer.WriteStringValue("sampleコード", Sampleコード);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
