// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace NasokiKoide.DXSuite.Models {
    /// <summary>
    /// 仕分け先別のOCR処理一覧
    /// </summary>
    public class StatusSortingUnitResponseV2_statusList : IAdditionalDataHolder, IParsable 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>仕分け先の読み取りユニットID ※ 仕分けされたページがないか、OCRに送信していない仕分け先 は0が設定されます。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReadingUnitId { get; set; }
#nullable restore
#else
        public string ReadingUnitId { get; set; }
#endif
        /// <summary>OCR送信対象件数</summary>
        public int? SendCountAll { get; set; }
        /// <summary>OCR送信エラー件数(データ化失敗件数)</summary>
        public int? SendCountFailure { get; set; }
        /// <summary>OCR送信済み件数(データ化完了件数)</summary>
        public int? SendCountSuccess { get; set; }
        /// <summary>仕分けステータスを表すコード値</summary>
        public int? StatusCode { get; set; }
        /// <summary>ステータス名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusName { get; set; }
#nullable restore
#else
        public string StatusName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="StatusSortingUnitResponseV2_statusList"/> and sets the default values.
        /// </summary>
        public StatusSortingUnitResponseV2_statusList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="StatusSortingUnitResponseV2_statusList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static StatusSortingUnitResponseV2_statusList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new StatusSortingUnitResponseV2_statusList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"readingUnitId", n => { ReadingUnitId = n.GetStringValue(); } },
                {"sendCountAll", n => { SendCountAll = n.GetIntValue(); } },
                {"sendCountFailure", n => { SendCountFailure = n.GetIntValue(); } },
                {"sendCountSuccess", n => { SendCountSuccess = n.GetIntValue(); } },
                {"statusCode", n => { StatusCode = n.GetIntValue(); } },
                {"statusName", n => { StatusName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("readingUnitId", ReadingUnitId);
            writer.WriteIntValue("sendCountAll", SendCountAll);
            writer.WriteIntValue("sendCountFailure", SendCountFailure);
            writer.WriteIntValue("sendCountSuccess", SendCountSuccess);
            writer.WriteIntValue("statusCode", StatusCode);
            writer.WriteStringValue("statusName", StatusName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
