// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Wf.Api.Atypical;
using NasokiKoide.DXSuite.Wf.Api.Fullocr;
using NasokiKoide.DXSuite.Wf.Api.Standard;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace NasokiKoide.DXSuite.Wf.Api {
    /// <summary>
    /// Builds and executes requests for operations under \wf\api
    /// </summary>
    public class ApiRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The atypical property</summary>
        public AtypicalRequestBuilder Atypical
        {
            get => new AtypicalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fullocr property</summary>
        public FullocrRequestBuilder Fullocr
        {
            get => new FullocrRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The standard property</summary>
        public StandardRequestBuilder Standard
        {
            get => new StandardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wf/api", rawUrl)
        {
        }
    }
}
