// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NasokiKoide.DXSuite.Sorter.Api.V1.Send {
    /// <summary>
    /// Builds and executes requests for operations under \Sorter\api\v1\send
    /// </summary>
    public class SendRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>
        /// Instantiates a new <see cref="SendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Sorter/api/v1/send?sortingUnitId={sortingUnitId}{&userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="SendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Sorter/api/v1/send?sortingUnitId={sortingUnitId}{&userId*}", rawUrl)
        {
        }
        /// <summary>
        /// 仕分けユニットIDで仕分けした結果をOCRに転送します。
        /// </summary>
        /// <returns>A <see cref="SendSortingResultResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 406 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="Model__error_response_v1__ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<SendSortingResultResponse?> PostAsync(Action<RequestConfiguration<SendRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<SendSortingResultResponse> PostAsync(Action<RequestConfiguration<SendRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"400", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"401", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"404", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"406", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"500", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"XXX", Model__error_response_v1__ErrorResponse.CreateFromDiscriminatorValue},
            };
            return await RequestAdapter.SendAsync<SendSortingResultResponse>(requestInfo, SendSortingResultResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 仕分けユニットIDで仕分けした結果をOCRに転送します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<SendRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<SendRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="SendRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public SendRequestBuilder WithUrl(string rawUrl)
        {
            return new SendRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 仕分けユニットIDで仕分けした結果をOCRに転送します。
        /// </summary>
        public class SendRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortingUnitId")]
            public string? SortingUnitId { get; set; }
#nullable restore
#else
            [QueryParameter("sortingUnitId")]
            public string SortingUnitId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("userId")]
            public string? UserId { get; set; }
#nullable restore
#else
            [QueryParameter("userId")]
            public string UserId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class SendRequestBuilderPostRequestConfiguration : RequestConfiguration<SendRequestBuilderPostQueryParameters> 
        {
        }
    }
}
