// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Pages.Images {
    /// <summary>
    /// Builds and executes requests for operations under \ConsoleWeb\api\v1\reading\pages\images
    /// </summary>
    public class ImagesRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>
        /// Instantiates a new <see cref="ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/pages/images{?filenameType*,readingPageId*,readingUnitId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/pages/images{?filenameType*,readingPageId*,readingUnitId*}", rawUrl)
        {
        }
        /// <summary>
        /// 読取ページの画像をZIPファイルで取得します。
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="Model__error_response_v1__ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<ImagesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<ImagesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"400", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"401", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"404", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"500", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"XXX", Model__error_response_v1__ErrorResponse.CreateFromDiscriminatorValue},
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 読取ページの画像をZIPファイルで取得します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<ImagesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<ImagesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="ImagesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public ImagesRequestBuilder WithUrl(string rawUrl)
        {
            return new ImagesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 読取ページの画像をZIPファイルで取得します。
        /// </summary>
        public class ImagesRequestBuilderGetQueryParameters 
        {
            /// <summary>1: ページID, 2: アップロード時のファイル名, 無指定の場合はページIDとなります。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filenameType")]
            public string? FilenameType { get; set; }
#nullable restore
#else
            [QueryParameter("filenameType")]
            public string FilenameType { get; set; }
#endif
            /// <summary>※読取ユニットID、読取ページIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("readingPageId")]
            public string? ReadingPageId { get; set; }
#nullable restore
#else
            [QueryParameter("readingPageId")]
            public string ReadingPageId { get; set; }
#endif
            /// <summary>※読取ユニットID、読取ページIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("readingUnitId")]
            public string? ReadingUnitId { get; set; }
#nullable restore
#else
            [QueryParameter("readingUnitId")]
            public string ReadingUnitId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ImagesRequestBuilderGetRequestConfiguration : RequestConfiguration<ImagesRequestBuilderGetQueryParameters> 
        {
        }
    }
}
