// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NasokiKoide.DXSuite.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NasokiKoide.DXSuite.ConsoleWeb.Api.V1.Reading.Parts {
    /// <summary>
    /// Builds and executes requests for operations under \ConsoleWeb\api\v1\reading\parts
    /// </summary>
    public class PartsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>
        /// Instantiates a new <see cref="PartsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PartsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/parts{?readingPageId*,readingPartsId*,readingUnitId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="PartsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PartsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ConsoleWeb/api/v1/reading/parts{?readingPageId*,readingPartsId*,readingUnitId*}", rawUrl)
        {
        }
        /// <summary>
        /// 読取パーツの情報を取得します。
        /// </summary>
        /// <returns>A List&lt;GetReadingPartsResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 406 status code</exception>
        /// <exception cref="Model__error_response_v1__BadRequestErrorResponse">When receiving a 500 status code</exception>
        /// <exception cref="Model__error_response_v1__ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<GetReadingPartsResponse>?> GetAsync(Action<RequestConfiguration<PartsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<GetReadingPartsResponse>> GetAsync(Action<RequestConfiguration<PartsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"400", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"401", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"404", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"406", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"500", Model__error_response_v1__BadRequestErrorResponse.CreateFromDiscriminatorValue},
                {"XXX", Model__error_response_v1__ErrorResponse.CreateFromDiscriminatorValue},
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<GetReadingPartsResponse>(requestInfo, GetReadingPartsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.ToList();
        }
        /// <summary>
        /// 読取パーツの情報を取得します。
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<PartsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<PartsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="PartsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public PartsRequestBuilder WithUrl(string rawUrl)
        {
            return new PartsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 読取パーツの情報を取得します。
        /// </summary>
        public class PartsRequestBuilderGetQueryParameters 
        {
            /// <summary>複数をカンマ区切りで指定可能 ※読取ユニットID、読取ページID、読取パーツIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("readingPageId")]
            public string? ReadingPageId { get; set; }
#nullable restore
#else
            [QueryParameter("readingPageId")]
            public string ReadingPageId { get; set; }
#endif
            /// <summary>複数をカンマ区切りで指定可能 ※読取ユニットID、読取ページID、読取パーツIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("readingPartsId")]
            public string? ReadingPartsId { get; set; }
#nullable restore
#else
            [QueryParameter("readingPartsId")]
            public string ReadingPartsId { get; set; }
#endif
            /// <summary>１つのユニットのみ指定可能 ※読取ユニットID、読取ページID、読取パーツIDのうち、1つは指定必須。(複数指定不可)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("readingUnitId")]
            public string? ReadingUnitId { get; set; }
#nullable restore
#else
            [QueryParameter("readingUnitId")]
            public string ReadingUnitId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class PartsRequestBuilderGetRequestConfiguration : RequestConfiguration<PartsRequestBuilderGetQueryParameters> 
        {
        }
    }
}
